trigger:
- test1
pool:
  vmImage: 'macos-latest'
steps:

- task: Xcode@5
  inputs:
    actions: 'archive' # build, clean, test, analyze, and archive
    scheme: $('actavivoIOS')
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: $('./Actavivo/ios/actavivo.xcworkspace')
    xcodeVersion: 'default'
    packageApp: true
    signingOption: 'default'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)' 
    exportMethod: $(ExportMethod)
    exportOptions: 'plist'
    exportOptionsPlist: $('pipelines/export.debug.plist')
    archivePath: '$(Build.ArtifactStagingDirectory)/pack'
    args: '-xcconfig release.xcconfig'
