trigger:
- test
pool:
  vmImage: 'macos-latest'
steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: './Actavivo
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: $('IOS-Distro.p12') #IOS-Dev.p12 IOS-Distro.p12
  certPwd: '$(CertPW)'
    keychain: 'temp'
- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: $('AV_App_Store.mobileprovision'  #'AV_Test_Profile.mobileprovision' 'AV_App_Store.mobileprovision')
    removeProfile: true
- task: CocoaPods@0
  inputs:
    workingDirectory: './Actavivo/ios'
    forceRepoUpdate: false
- task: Xcode@5
  displayName: Build
  timeoutInMinutes: 15
  inputs:
    actions: 'archive' # build, clean, test, analyze, and archive
    scheme: $('actavivoIOS')
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: $('./Actavivo/ios/actavivo.xcworkspace')
    xcodeVersion: 'default'
    packageApp: true
    signingOption: 'default'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)' 
    exportMethod: $(ExportMethod)
    exportOptions: 'plist'
    exportOptionsPlist: $('pipelines/export.debug.plist')
    archivePath: '$(Build.ArtifactStagingDirectory)/pack'
    args: '-xcconfig release.xcconfig'
- task: AppStoreRelease@1
condition:ne(variables['Build.Reason'], 'PullRequest')
  inputs:
    serviceEndpoint: $(AppStoreServiceConnectionName)
    appIdentifier: $(BundleID)
    appType: 'iOS'
    ipaPath: '**/*.ipa'
    releaseTrack: 'TestFlight'
    shouldSkipWaitingForProcessing: true # don't wait
    shouldSkipSubmission: true # don't auto send to testers
  env:
    FASTLANE_ITC_TEAM_ID: $(ITCTeamID)