trigger:
  branches:
    include:
    - main
  paths:
    include:
      - 'iOS'

pool:
  vmImage: 'macos-latest'

steps:
  - task: CocoaPods@0
    displayName: 'installing pods'
    inputs:
      workingDirectory: 'iOS/ProjectName'
      forceRepoUpdate: false

  - task: DownloadSecureFile@1
    displayName: 'Download project certificate'
    inputs:
      secureFile: 'certificates.p12'

  - task: DownloadSecureFile@1
    displayName: 'Download provisional certificate'
    inputs:
      secureFile: 'nameOfCertificate.mobileprovision'

  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'certificates.p12'
      certPwd: '$(p12password)'
      keychain: 'temp'

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: 'nameOfCertificate.mobileprovision'

  - task: Xcode@5
    displayName: 'Build the app using Xcode'
    inputs:
      actions: 'build'
      sdk: 'iphoneos'
      scheme: 'projectName'
      xcWorkspacePath: 'iOS/FolderName/projectName.xcworkspace'
      packageApp: true
      signingOption: 'manual'

  - task: Xcode@5
    displayName: 'Run XCTest/XCUITest'
    inputs:
      actions: 'test'
      sdk: 'iphonesimulator'
      xcWorkspacePath: 'iOS/FolderName/projectName.xcworkspace'
      scheme: 'projectName'
      xcodeVersion: 'default'
      useXcpretty: true
      publishJUnitResults: true
      destinationPlatformOption: 'iOS' # Optional. Options: default, iOS, tvOS, macOS, custom
      destinationPlatform: 'iOS Simulator'
      destinationTypeOption: 'simulators' # Optional. Options: simulators, devices
      destinationSimulators: 'iPhone 8' # Optional. Default value: iPhone8 for Xcode 11 and iPhone 7 for other iOS projects; Apple TV for tvOS projects.
   
  - task: PublishTestResults@2
    displayName: 'Publishing test results'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/junit.xml'
      mergeTestResults: true
      failTaskOnFailedTests: true